### ISSUE TITLE
where are all the cute user avatars located?

### ISSUE THREAD

**Issue by randomseed42** [ric2b/Vivaldi-browser#7]
and am I allowed to use them elsewhere?

**Comment by randomseed42** [comment]
got it :)
https://github.com/ric2b/Vivaldi-browser/tree/master/app/resources/theme/default_100_percent/vivaldi/avatars

**Comment by mathieucaroff** [comment]
For those who'd want to grab the avatars without downloading the whole repo, you can use:

https://download-directory.github.io/

Or, since I did download them already, here's the zipped directory: [ric2b Vivaldi-browser master app-resources_theme_default_100_percent_vivaldi_avatars.zip](https://github.com/ric2b/Vivaldi-browser/files/6134456/ric2b.Vivaldi-browser.master.app-resources_theme_default_100_percent_vivaldi_avatars.zip)

**Comment by randomseed42** [comment]
> For those who'd want to grab the avatars without downloading the whole repo, you can use:
> 
> 
> 
> https://download-directory.github.io/
> 
> 
> 
> Or, since I did download them already, here's the zipped directory: [ric2b Vivaldi-browser master app-resources_theme_default_100_percent_vivaldi_avatars.zip](https://github.com/ric2b/Vivaldi-browser/files/6134456/ric2b.Vivaldi-browser.master.app-resources_theme_default_100_percent_vivaldi_avatars.zip)
> 
> 

Thank you Mathieu! I'v also tried github1s, svn checkout and chrome-pal-customizer to get them😋
